(ns playground.2)


(defn fib-seq []
  "Generate lazy sequence fibonacci starting from 1 & 2"
  ((fn rfib [a b]
     (cons a (lazy-seq (rfib b (+ a b)))))
    1 2))


(defn sum-even-fib
  "
  From: https://projecteuler.net/problem=2

  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms."
  [max]
  (->>
    (take-while #(< % max) (fib-seq))
    (filter even?)
    (reduce +)))

(println (sum-even-fib 4000000))